predict_sets = {
	"Program -> ProgramHead DeclarePart ProgramBody .": {'PROGRAM'},
	"ProgramHead -> PROGRAM ProgramName": {'PROGRAM'},
	"ProgramName -> ID": {'ID'},
	"DeclarePart -> TypeDec VarDec ProcDec": {'TYPE', 'VAR', 'BEGIN', 'PROCEDURE'},
	"TypeDec -> ε": {'BEGIN', 'VAR', 'PROCEDURE'},
	"TypeDec -> TypeDeclaration": {'TYPE'},
	"TypeDeclaration -> TYPE TypeDecList": {'TYPE'},
	"TypeDecList -> TypeId = TypeName ; TypeDecMore": {'ID'},
	"TypeDecMore -> ε": {'BEGIN', 'VAR', 'PROCEDURE'},
	"TypeDecMore -> TypeDecList": {'ID'},
	"TypeId -> ID": {'ID'},
	"TypeName -> BaseType": {'CHAR', 'INTEGER'},
	"TypeName -> StructureType": {'RECORD', 'ARRAY'},
	"TypeName -> ID": {'ID'},
	"BaseType -> INTEGER": {'INTEGER'},
	"BaseType -> CHAR": {'CHAR'},
	"StructureType -> ArrayType": {'ARRAY'},
	"StructureType -> RecType": {'RECORD'},
	"ArrayType -> ARRAY [ Low .. Top ] OF BaseType": {'ARRAY'},
	"Low -> INTC": {'INTC'},
	"Top -> INTC": {'INTC'},
	"RecType -> RECORD FieldDecList END": {'RECORD'},
	"FieldDecList -> BaseType IdList ; FieldDecMore": {'CHAR', 'INTEGER'},
	"FieldDecList -> ArrayType IdList ; FieldDecMore": {'ARRAY'},
	"FieldDecMore -> ε": {'END'},
	"FieldDecMore -> FieldDecList": {'INTEGER', 'CHAR', 'ARRAY'},
	"IdList -> ID IdMore": {'ID'},
	"IdMore -> ε": {';'},
	"IdMore -> , IdList": {','},
	"VarDec -> ε": {'BEGIN', 'PROCEDURE'},
	"VarDec -> VarDeclaration": {'VAR'},
	"VarDeclaration -> VAR VarDecList": {'VAR'},
	"VarDecList -> TypeName VarIdList ; VarDecMore": {'ARRAY', 'RECORD', 'INTEGER', 'CHAR', 'ID'},
	"VarDecMore -> ε": {'BEGIN', 'PROCEDURE'},
	"VarDecMore -> VarDecList": {'ARRAY', 'RECORD', 'INTEGER', 'CHAR', 'ID'},
	"VarIdList -> ID VarIdMore": {'ID'},
	"VarIdMore -> ε": {';'},
	"VarIdMore -> , VarIdList": {','},
	"ProcDec -> ε": {'BEGIN'},
	"ProcDec -> ProcDeclaration": {'PROCEDURE'},
	"ProcDeclaration -> PROCEDURE ProcName ( ParamList ) ; ProcDecPart ProcBody ProcDecMore": {'PROCEDURE'},
	"ProcDecMore -> ε": {'BEGIN'},
	"ProcDecMore -> ProcDeclaration": {'PROCEDURE'},
	"ProcName -> ID": {'ID'},
	"ParamList -> ε": {')'},
	"ParamList -> ParamDecList": {'VAR', 'ARRAY', 'RECORD', 'INTEGER', 'CHAR', 'ID'},
	"ParamDecList -> Param ParamMore": {'VAR', 'ARRAY', 'RECORD', 'INTEGER', 'CHAR', 'ID'},
	"ParamMore -> ε": {')'},
	"ParamMore -> ; ParamDecList": {';'},
	"Param -> TypeName FormList": {'ARRAY', 'RECORD', 'INTEGER', 'CHAR', 'ID'},
	"Param -> VAR TypeName FormList": {'VAR'},
	"FormList -> ID FidMore": {'ID'},
	"FidMore -> ε": {';', ')'},
	"FidMore -> , FormList": {','},
	"ProcDecPart -> DeclarePart": {'TYPE', 'PROCEDURE', 'BEGIN', 'VAR'},
	"ProcBody -> ProgramBody": {'BEGIN'},
	"ProgramBody -> BEGIN StmList END": {'BEGIN'},
	"StmList -> Stm StmMore": {'READ', 'IF', 'RETURN', 'WRITE', 'WHILE', 'ID'},
	"StmMore -> ε": {'ELSE', 'FI', 'ENDWH', 'END'},
	"StmMore -> ; StmList": {';'},
	"Stm -> ConditionalStm": {'IF'},
	"Stm -> LoopStm": {'WHILE'},
	"Stm -> InputStm": {'READ'},
	"Stm -> OutputStm": {'WRITE'},
	"Stm -> ReturnStm": {'RETURN'},
	"Stm -> ID AssCall": {'ID'},
	"AssCall -> AssignmentRest": {'[', ':=', '.'},
	"AssCall -> CallStmRest": {'('},
	"AssignmentRest -> VariMore := Exp": {'[', ':=', '.'},
	"ConditionalStm -> IF RelExp THEN StmList ELSE StmList FI": {'IF'},
	"LoopStm -> WHILE RelExp DO StmList ENDWH": {'WHILE'},
	"InputStm -> READ ( Invar )": {'READ'},
	"Invar -> ID": {'ID'},
	"OutputStm -> WRITE ( Exp )": {'WRITE'},
	"ReturnStm -> RETURN ( Exp )": {'RETURN'},
	"CallStmRest -> ( ActParamList )": {'('},
	"ActParamList -> ε": {')'},
	"ActParamList -> Exp ActParamMore": {'(', 'INTC', 'ID'},
	"ActParamMore -> ε": {')'},
	"ActParamMore -> , ActParamList": {','},
	"RelExp -> Exp OtherRelE": {'(', 'INTC', 'ID'},
	"OtherRelE -> CmpOp Exp": {'<', '='},
	"Exp -> Term OtherTerm": {'(', 'INTC', 'ID'},
	"OtherTerm -> ε": {'ELSE', ',', ';', '<', 'FI', '=', 'THEN', 'END', ']', 'ENDWH', 'DO', ')'},
	"OtherTerm -> AddOp Exp": {'-', '+'},
	"Term -> Factor OtherFactor": {'(', 'INTC', 'ID'},
	"OtherFactor -> ε": {'-', ',', 'ELSE', '+', ';', '<', 'FI', '=', 'THEN', 'END', ']', 'ENDWH', 'DO', ')'},
	"OtherFactor -> MultOp Term": {'/', '*'},
	"Factor -> ( Exp )": {'('},
	"Factor -> INTC": {'INTC'},
	"Factor -> Variable": {'ID'},
	"Variable -> ID VariMore": {'ID'},
	"VariMore -> ε": {'-', ',', 'ELSE', 'DO', ';', '*', ']', '+', '<', 'FI', '=', 'THEN', 'END', '/', 'ENDWH', ':=', ')'},
	"VariMore -> [ Exp ]": {'['},
	"VariMore -> . FieldVar": {'.'},
	"FieldVar -> ID FieldVarMore": {'ID'},
	"FieldVarMore -> ε": {'-', ',', 'ELSE', 'DO', ';', '*', ']', '+', '<', 'FI', '=', 'THEN', 'END', '/', 'ENDWH', ':=', ')'},
	"FieldVarMore -> [ Exp ]": {'['},
	"CmpOp -> <": {'<'},
	"CmpOp -> =": {'='},
	"AddOp -> +": {'+'},
	"AddOp -> -": {'-'},
	"MultOp -> *": {'*'},
	"MultOp -> /": {'/'},
}