first_sets = {
	"OutputStm": {'WRITE'},
	"VarDecMore": {'ID', 'ε', 'ARRAY', 'INTEGER', 'RECORD', 'CHAR'},
	"StructureType": {'ARRAY', 'RECORD'},
	"FieldVar": {'ID'},
	"FieldDecList": {'ARRAY', 'INTEGER', 'CHAR'},
	"ProgramName": {'ID'},
	"StmList": {'RETURN', 'WHILE', 'ID', 'READ', 'IF', 'WRITE'},
	"AddOp": {'+', '-'},
	"StmMore": {';', 'ε'},
	"ProgramBody": {'BEGIN'},
	"ProcDec": {'PROCEDURE', 'ε'},
	"ActParamList": {'(', 'ID', 'ε', 'INTC'},
	"FidMore": {',', 'ε'},
	"ArrayType": {'ARRAY'},
	"TypeName": {'ARRAY', 'INTEGER', 'RECORD', 'ID', 'CHAR'},
	"TypeDecList": {'ID'},
	"AssignmentRest": {':=', '.', '['},
	"TypeDecMore": {'ID', 'ε'},
	"TypeDec": {'TYPE', 'ε'},
	"ProcDecPart": {'TYPE', 'ε', 'VAR', 'PROCEDURE'},
	"OtherTerm": {'+', 'ε', '-'},
	"AssCall": {'.', ':=', '(', '['},
	"MultOp": {'/', '*'},
	"RelExp": {'(', 'ID', 'INTC'},
	"VariMore": {'.', '[', 'ε'},
	"ReturnStm": {'RETURN'},
	"IdMore": {',', 'ε'},
	"FormList": {'ID'},
	"ParamList": {'ID', 'ε', 'ARRAY', 'INTEGER', 'RECORD', 'VAR', 'CHAR'},
	"Program": {'PROGRAM'},
	"FieldVarMore": {'[', 'ε'},
	"VarIdMore": {',', 'ε'},
	"Low": {'INTC'},
	"DeclarePart": {'TYPE', 'ε', 'VAR', 'PROCEDURE'},
	"BaseType": {'INTEGER', 'CHAR'},
	"Top": {'INTC'},
	"Term": {'(', 'ID', 'INTC'},
	"LoopStm": {'WHILE'},
	"CmpOp": {'<', '='},
	"VarDeclaration": {'VAR'},
	"ParamMore": {';', 'ε'},
	"Invar": {'ID'},
	"IdList": {'ID'},
	"TypeId": {'ID'},
	"RecType": {'RECORD'},
	"OtherRelE": {'<', '='},
	"Param": {'ID', 'ARRAY', 'INTEGER', 'RECORD', 'VAR', 'CHAR'},
	"TypeDeclaration": {'TYPE'},
	"Exp": {'(', 'ID', 'INTC'},
	"Factor": {'(', 'ID', 'INTC'},
	"ProcName": {'ID'},
	"ActParamMore": {',', 'ε'},
	"ProcDecMore": {'PROCEDURE', 'ε'},
	"ProgramHead": {'PROGRAM'},
	"VarIdList": {'ID'},
	"CallStmRest": {'('},
	"ProcBody": {'BEGIN'},
	"VarDecList": {'ID', 'ARRAY', 'INTEGER', 'RECORD', 'CHAR'},
	"ConditionalStm": {'IF'},
	"Variable": {'ID'},
	"InputStm": {'READ'},
	"Stm": {'IF', 'WHILE', 'RETURN', 'ID', 'WRITE', 'READ'},
	"ParamDecList": {'ID', 'ARRAY', 'INTEGER', 'RECORD', 'VAR', 'CHAR'},
	"FieldDecMore": {'ARRAY', 'INTEGER', 'CHAR', 'ε'},
	"VarDec": {'VAR', 'ε'},
	"ProcDeclaration": {'PROCEDURE'},
	"OtherFactor": {'/', '*', 'ε'},
	".": {'.'},
	"END.": {'END.'},
	"PROCEDURE": {'PROCEDURE'},
	"READ": {'READ'},
	"-": {'-'},
	"id": {'id'},
	"FI": {'FI'},
	"BEGIN": {'BEGIN'},
	"ENDWH": {'ENDWH'},
	"INTC": {'INTC'},
	"OF": {'OF'},
	"*": {'*'},
	",": {','},
	"(": {'('},
	"[": {'['},
	"<": {'<'},
	"ARRAY": {'ARRAY'},
	"VAR": {'VAR'},
	"CHAR": {'CHAR'},
	"DO": {'DO'},
	";": {';'},
	"ID": {'ID'},
	"PROGRAM": {'PROGRAM'},
	"END": {'END'},
	"=": {'='},
	"/": {'/'},
	"THEN": {'THEN'},
	"WRITE": {'WRITE'},
	"..": {'..'},
	"RETURN": {'RETURN'},
	"WHILE": {'WHILE'},
	")": {')'},
	"ε": {'ε'},
	"INTEGER": {'INTEGER'},
	"RECORD": {'RECORD'},
	"+": {'+'},
	"TYPE": {'TYPE'},
	"ELSE": {'ELSE'},
	"IF": {'IF'},
	":=": {':='},
	"]": {']'},
}