follow_sets = {
	"OutputStm": {';', 'END', 'ELSE', 'FI', 'ENDWH'},
	"VarDecMore": {'BEGIN', 'PROCEDURE'},
	"StructureType": {'ID', ';'},
	"FieldVar": {'DO', ';', '-', '=', 'END', '/', 'THEN', 'FI', 'ENDWH', '*', ')', ',', '<', '+', 'ELSE', ':=', ']'},
	"FieldDecList": {'END'},
	"ProgramName": {'PROCEDURE', 'TYPE', 'VAR', 'BEGIN'},
	"StmList": {'END', 'ELSE', 'FI', 'ENDWH'},
	"AddOp": {'(', 'ID', 'INTC'},
	"StmMore": {'END', 'ELSE', 'FI', 'ENDWH'},
	"ProgramBody": {'.', 'BEGIN', 'PROCEDURE'},
	"ProcDec": {'BEGIN'},
	"ActParamList": {')'},
	"FidMore": {';', ')'},
	"ArrayType": {';', 'ID'},
	"TypeName": {'ID', ';'},
	"TypeDecList": {'VAR', 'BEGIN', 'PROCEDURE'},
	"AssignmentRest": {';', 'END', 'ELSE', 'FI', 'ENDWH'},
	"TypeDecMore": {'VAR', 'BEGIN', 'PROCEDURE'},
	"TypeDec": {'VAR', 'BEGIN', 'PROCEDURE'},
	"ProcDecPart": {'BEGIN'},
	"OtherTerm": {'DO', ';', '=', 'END', 'THEN', 'FI', 'ENDWH', ')', ',', '<', 'ELSE', ']'},
	"AssCall": {';', 'END', 'ELSE', 'FI', 'ENDWH'},
	"MultOp": {'(', 'ID', 'INTC'},
	"RelExp": {'DO', 'THEN'},
	"VariMore": {'DO', ';', '-', '=', 'END', '/', 'THEN', 'FI', 'ENDWH', '*', ')', ',', '<', '+', 'ELSE', ':=', ']'},
	"ReturnStm": {';', 'END', 'ELSE', 'FI', 'ENDWH'},
	"IdMore": {';'},
	"FormList": {';', ')'},
	"ParamList": {')'},
	"Program": {'#'},
	"FieldVarMore": {'DO', ';', '-', '=', 'END', '/', 'THEN', 'FI', 'ENDWH', '*', ')', ',', '<', '+', 'ELSE', ':=', ']'},
	"VarIdMore": {';'},
	"Low": {'..'},
	"DeclarePart": {'BEGIN'},
	"BaseType": {'ID', ';'},
	"Top": {']'},
	"Term": {'DO', ';', '-', '=', 'END', 'THEN', 'FI', 'ENDWH', ')', ',', '<', '+', 'ELSE', ']'},
	"LoopStm": {';', 'END', 'ELSE', 'FI', 'ENDWH'},
	"CmpOp": {'(', 'ID', 'INTC'},
	"VarDeclaration": {'BEGIN', 'PROCEDURE'},
	"ParamMore": {')'},
	"Invar": {')'},
	"IdList": {';'},
	"TypeId": {'='},
	"RecType": {'ID', ';'},
	"OtherRelE": {'DO', 'THEN'},
	"Param": {';', ')'},
	"TypeDeclaration": {'VAR', 'BEGIN', 'PROCEDURE'},
	"Exp": {'DO', ';', ')', ',', '<', '=', 'END', 'THEN', 'ELSE', 'FI', 'ENDWH', ']'},
	"Factor": {'DO', ';', '-', '=', 'END', '/', 'THEN', 'FI', 'ENDWH', '*', ')', ',', '<', '+', 'ELSE', ']'},
	"ProcName": {'('},
	"ActParamMore": {')'},
	"ProcDecMore": {'BEGIN'},
	"ProgramHead": {'PROCEDURE', 'TYPE', 'VAR', 'BEGIN'},
	"VarIdList": {';'},
	"CallStmRest": {';', 'END', 'ELSE', 'FI', 'ENDWH'},
	"ProcBody": {'BEGIN', 'PROCEDURE'},
	"VarDecList": {'BEGIN', 'PROCEDURE'},
	"ConditionalStm": {';', 'END', 'ELSE', 'FI', 'ENDWH'},
	"Variable": {'DO', ';', '-', '=', 'END', '/', 'THEN', 'FI', 'ENDWH', '*', ')', ',', '<', '+', 'ELSE', ']'},
	"InputStm": {';', 'END', 'ELSE', 'FI', 'ENDWH'},
	"Stm": {';', 'END', 'ELSE', 'FI', 'ENDWH'},
	"ParamDecList": {')'},
	"FieldDecMore": {'END'},
	"VarDec": {'BEGIN', 'PROCEDURE'},
	"ProcDeclaration": {'BEGIN'},
	"OtherFactor": {'DO', ';', '-', '=', 'END', 'THEN', 'FI', 'ENDWH', ')', ',', '<', '+', 'ELSE', ']'},
}