predict_sets = {
	('Program', 'ProgramHead DeclarePart ProgramBody .'): {'PROGRAM'},
	('ProgramHead', 'PROGRAM ProgramName'): {'PROGRAM'},
	('ProgramName', 'ID'): {'ID'},
	('DeclarePart', 'TypeDec VarDec ProcDec'): {'TYPE', 'BEGIN', 'PROCEDURE', 'VAR'},
	('TypeDec', 'ε'): {'BEGIN', 'VAR', 'PROCEDURE'},
	('TypeDec', 'TypeDeclaration'): {'TYPE'},
	('TypeDeclaration', 'TYPE TypeDecList'): {'TYPE'},
	('TypeDecList', 'TypeId = TypeName ; TypeDecMore'): {'ID'},
	('TypeDecMore', 'ε'): {'BEGIN', 'VAR', 'PROCEDURE'},
	('TypeDecMore', 'TypeDecList'): {'ID'},
	('TypeId', 'ID'): {'ID'},
	('TypeName', 'BaseType'): {'INTEGER', 'CHAR'},
	('TypeName', 'StructureType'): {'RECORD', 'ARRAY'},
	('TypeName', 'ID'): {'ID'},
	('BaseType', 'INTEGER'): {'INTEGER'},
	('BaseType', 'CHAR'): {'CHAR'},
	('StructureType', 'ArrayType'): {'ARRAY'},
	('StructureType', 'RecType'): {'RECORD'},
	('ArrayType', 'ARRAY [ Low .. Top ] OF BaseType'): {'ARRAY'},
	('Low', 'INTC'): {'INTC'},
	('Top', 'INTC'): {'INTC'},
	('RecType', 'RECORD FieldDecList END'): {'RECORD'},
	('FieldDecList', 'BaseType IdList ; FieldDecMore'): {'INTEGER', 'CHAR'},
	('FieldDecList', 'ArrayType IdList ; FieldDecMore'): {'ARRAY'},
	('FieldDecMore', 'ε'): {'END'},
	('FieldDecMore', 'FieldDecList'): {'INTEGER', 'CHAR', 'ARRAY'},
	('IdList', 'ID IdMore'): {'ID'},
	('IdMore', 'ε'): {';'},
	('IdMore', ', IdList'): {','},
	('VarDec', 'ε'): {'PROCEDURE', 'BEGIN'},
	('VarDec', 'VarDeclaration'): {'VAR'},
	('VarDeclaration', 'VAR VarDecList'): {'VAR'},
	('VarDecList', 'TypeName VarIdList ; VarDecMore'): {'RECORD', 'ID', 'INTEGER', 'CHAR', 'ARRAY'},
	('VarDecMore', 'ε'): {'PROCEDURE', 'BEGIN'},
	('VarDecMore', 'VarDecList'): {'RECORD', 'ID', 'INTEGER', 'CHAR', 'ARRAY'},
	('VarIdList', 'ID VarIdMore'): {'ID'},
	('VarIdMore', 'ε'): {';'},
	('VarIdMore', ', VarIdList'): {','},
	('ProcDec', 'ε'): {'BEGIN'},
	('ProcDec', 'ProcDeclaration'): {'PROCEDURE'},
	('ProcDeclaration', 'PROCEDURE ProcName ( ParamList ) ; ProcDecPart ProcBody ProcDecMore'): {'PROCEDURE'},
	('ProcDecMore', 'ε'): {'BEGIN'},
	('ProcDecMore', 'ProcDeclaration'): {'PROCEDURE'},
	('ProcName', 'ID'): {'ID'},
	('ParamList', 'ε'): {')'},
	('ParamList', 'ParamDecList'): {'RECORD', 'VAR', 'ID', 'INTEGER', 'CHAR', 'ARRAY'},
	('ParamDecList', 'Param ParamMore'): {'RECORD', 'VAR', 'ID', 'INTEGER', 'CHAR', 'ARRAY'},
	('ParamMore', 'ε'): {')'},
	('ParamMore', '; ParamDecList'): {';'},
	('Param', 'TypeName FormList'): {'RECORD', 'ID', 'INTEGER', 'CHAR', 'ARRAY'},
	('Param', 'VAR TypeName FormList'): {'VAR'},
	('FormList', 'ID FidMore'): {'ID'},
	('FidMore', 'ε'): {')', ';'},
	('FidMore', ', FormList'): {','},
	('ProcDecPart', 'DeclarePart'): {'TYPE', 'BEGIN', 'PROCEDURE', 'VAR'},
	('ProcBody', 'ProgramBody'): {'BEGIN'},
	('ProgramBody', 'BEGIN StmList END'): {'BEGIN'},
	('StmList', 'Stm StmMore'): {'IF', 'WRITE', 'WHILE', 'ID', 'READ', 'RETURN'},
	('StmMore', 'ε'): {'END', 'ENDWH', 'FI', 'ELSE'},
	('StmMore', '; StmList'): {';'},
	('Stm', 'ConditionalStm'): {'IF'},
	('Stm', 'LoopStm'): {'WHILE'},
	('Stm', 'InputStm'): {'READ'},
	('Stm', 'OutputStm'): {'WRITE'},
	('Stm', 'ReturnStm'): {'RETURN'},
	('Stm', 'ID AssCall'): {'ID'},
	('AssCall', 'AssignmentRest'): {'.', ':=', '['},
	('AssCall', 'CallStmRest'): {'('},
	('AssignmentRest', 'VariMore := Exp'): {'.', ':=', '['},
	('ConditionalStm', 'IF RelExp THEN StmList ELSE StmList FI'): {'IF'},
	('LoopStm', 'WHILE RelExp DO StmList ENDWH'): {'WHILE'},
	('InputStm', 'READ ( Invar )'): {'READ'},
	('Invar', 'ID'): {'ID'},
	('OutputStm', 'WRITE ( Exp )'): {'WRITE'},
	('ReturnStm', 'RETURN ( Exp )'): {'RETURN'},
	('CallStmRest', '( ActParamList )'): {'('},
	('ActParamList', 'ε'): {')'},
	('ActParamList', 'Exp ActParamMore'): {'(', 'INTC', 'ID'},
	('ActParamMore', 'ε'): {')'},
	('ActParamMore', ', ActParamList'): {','},
	('RelExp', 'Exp OtherRelE'): {'(', 'INTC', 'ID'},
	('OtherRelE', 'CmpOp Exp'): {'<', '='},
	('Exp', 'Term OtherTerm'): {'(', 'INTC', 'ID'},
	('OtherTerm', 'ε'): {']', ',', '<', 'ENDWH', 'DO', '=', 'ELSE', 'END', 'FI', 'THEN', ')', ';'},
	('OtherTerm', 'AddOp Exp'): {'+', '-'},
	('Term', 'Factor OtherFactor'): {'(', 'INTC', 'ID'},
	('OtherFactor', 'ε'): {']', ',', '<', 'ENDWH', 'DO', '=', 'ELSE', '+', 'END', 'FI', 'THEN', ')', ';', '-'},
	('OtherFactor', 'MultOp Term'): {'/', '*'},
	('Factor', '( Exp )'): {'('},
	('Factor', 'INTC'): {'INTC'},
	('Factor', 'Variable'): {'ID'},
	('Variable', 'ID VariMore'): {'ID'},
	('VariMore', 'ε'): {'DO', 'END', '*', ';', '-', '/', ']', '<', 'ENDWH', '=', 'ELSE', '+', 'FI', 'THEN', ')', ':=', ','},
	('VariMore', '[ Exp ]'): {'['},
	('VariMore', '. FieldVar'): {'.'},
	('FieldVar', 'ID FieldVarMore'): {'ID'},
	('FieldVarMore', 'ε'): {'DO', 'END', '*', ';', '-', '/', ']', '<', 'ENDWH', '=', 'ELSE', '+', 'FI', 'THEN', ')', ':=', ','},
	('FieldVarMore', '[ Exp ]'): {'['},
	('CmpOp', '<'): {'<'},
	('CmpOp', '='): {'='},
	('AddOp', '+'): {'+'},
	('AddOp', '-'): {'-'},
	('MultOp', '*'): {'*'},
	('MultOp', '/'): {'/'},
}