predict_sets = {
	"('Program', 'ProgramHead DeclarePart ProgramBody .')": {'PROGRAM'},
	"('ProgramHead', 'PROGRAM ProgramName')": {'PROGRAM'},
	"('ProgramName', 'ID')": {'ID'},
	"('DeclarePart', 'TypeDec VarDec ProcDec')": {'VAR', 'TYPE', 'BEGIN', 'PROCEDURE'},
	"('TypeDec', 'ε')": {'VAR', 'BEGIN', 'PROCEDURE'},
	"('TypeDec', 'TypeDeclaration')": {'TYPE'},
	"('TypeDeclaration', 'TYPE TypeDecList')": {'TYPE'},
	"('TypeDecList', 'TypeId = TypeName ; TypeDecMore')": {'ID'},
	"('TypeDecMore', 'ε')": {'VAR', 'BEGIN', 'PROCEDURE'},
	"('TypeDecMore', 'TypeDecList')": {'ID'},
	"('TypeId', 'ID')": {'ID'},
	"('TypeName', 'BaseType')": {'INTEGER', 'CHAR'},
	"('TypeName', 'StructureType')": {'ARRAY', 'RECORD'},
	"('TypeName', 'ID')": {'ID'},
	"('BaseType', 'INTEGER')": {'INTEGER'},
	"('BaseType', 'CHAR')": {'CHAR'},
	"('StructureType', 'ArrayType')": {'ARRAY'},
	"('StructureType', 'RecType')": {'RECORD'},
	"('ArrayType', 'ARRAY [ Low .. Top ] OF BaseType')": {'ARRAY'},
	"('Low', 'INTC')": {'INTC'},
	"('Top', 'INTC')": {'INTC'},
	"('RecType', 'RECORD FieldDecList END')": {'RECORD'},
	"('FieldDecList', 'BaseType IdList ; FieldDecMore')": {'INTEGER', 'CHAR'},
	"('FieldDecList', 'ArrayType IdList ; FieldDecMore')": {'ARRAY'},
	"('FieldDecMore', 'ε')": {'END'},
	"('FieldDecMore', 'FieldDecList')": {'ARRAY', 'INTEGER', 'CHAR'},
	"('IdList', 'ID IdMore')": {'ID'},
	"('IdMore', 'ε')": {';'},
	"('IdMore', ', IdList')": {','},
	"('VarDec', 'ε')": {'BEGIN', 'PROCEDURE'},
	"('VarDec', 'VarDeclaration')": {'VAR'},
	"('VarDeclaration', 'VAR VarDecList')": {'VAR'},
	"('VarDecList', 'TypeName VarIdList ; VarDecMore')": {'ARRAY', 'INTEGER', 'RECORD', 'ID', 'CHAR'},
	"('VarDecMore', 'ε')": {'BEGIN', 'PROCEDURE'},
	"('VarDecMore', 'VarDecList')": {'ARRAY', 'INTEGER', 'RECORD', 'ID', 'CHAR'},
	"('VarIdList', 'ID VarIdMore')": {'ID'},
	"('VarIdMore', 'ε')": {';'},
	"('VarIdMore', ', VarIdList')": {','},
	"('ProcDec', 'ε')": {'BEGIN'},
	"('ProcDec', 'ProcDeclaration')": {'PROCEDURE'},
	"('ProcDeclaration', 'PROCEDURE ProcName ( ParamList ) ; ProcDecPart ProcBody ProcDecMore')": {'PROCEDURE'},
	"('ProcDecMore', 'ε')": {'BEGIN'},
	"('ProcDecMore', 'ProcDeclaration')": {'PROCEDURE'},
	"('ProcName', 'ID')": {'ID'},
	"('ParamList', 'ε')": {')'},
	"('ParamList', 'ParamDecList')": {'ARRAY', 'INTEGER', 'RECORD', 'VAR', 'ID', 'CHAR'},
	"('ParamDecList', 'Param ParamMore')": {'ARRAY', 'INTEGER', 'RECORD', 'VAR', 'ID', 'CHAR'},
	"('ParamMore', 'ε')": {')'},
	"('ParamMore', '; ParamDecList')": {';'},
	"('Param', 'TypeName FormList')": {'ARRAY', 'INTEGER', 'RECORD', 'ID', 'CHAR'},
	"('Param', 'VAR TypeName FormList')": {'VAR'},
	"('FormList', 'ID FidMore')": {'ID'},
	"('FidMore', 'ε')": {';', ')'},
	"('FidMore', ', FormList')": {','},
	"('ProcDecPart', 'DeclarePart')": {'VAR', 'TYPE', 'BEGIN', 'PROCEDURE'},
	"('ProcBody', 'ProgramBody')": {'BEGIN'},
	"('ProgramBody', 'BEGIN StmList END')": {'BEGIN'},
	"('StmList', 'Stm StmMore')": {'RETURN', 'WHILE', 'IF', 'ID', 'WRITE', 'READ'},
	"('StmMore', 'ε')": {'END', 'ENDWH', 'ELSE', 'FI'},
	"('StmMore', '; StmList')": {';'},
	"('Stm', 'ConditionalStm')": {'IF'},
	"('Stm', 'LoopStm')": {'WHILE'},
	"('Stm', 'InputStm')": {'READ'},
	"('Stm', 'OutputStm')": {'WRITE'},
	"('Stm', 'ReturnStm')": {'RETURN'},
	"('Stm', 'ID AssCall')": {'ID'},
	"('AssCall', 'AssignmentRest')": {':=', '.', '['},
	"('AssCall', 'CallStmRest')": {'('},
	"('AssignmentRest', 'VariMore := Exp')": {':=', '.', '['},
	"('ConditionalStm', 'IF RelExp THEN StmList ELSE StmList FI')": {'IF'},
	"('LoopStm', 'WHILE RelExp DO StmList ENDWH')": {'WHILE'},
	"('InputStm', 'READ ( Invar )')": {'READ'},
	"('Invar', 'ID')": {'ID'},
	"('OutputStm', 'WRITE ( Exp )')": {'WRITE'},
	"('ReturnStm', 'RETURN ( Exp )')": {'RETURN'},
	"('CallStmRest', '( ActParamList )')": {'('},
	"('ActParamList', 'ε')": {')'},
	"('ActParamList', 'Exp ActParamMore')": {'(', 'ID', 'INTC'},
	"('ActParamMore', 'ε')": {')'},
	"('ActParamMore', ', ActParamList')": {','},
	"('RelExp', 'Exp OtherRelE')": {'(', 'ID', 'INTC'},
	"('OtherRelE', 'CmpOp Exp')": {'<', '='},
	"('Exp', 'Term OtherTerm')": {'(', 'ID', 'INTC'},
	"('OtherTerm', 'ε')": {'DO', ';', ')', ',', '<', '=', 'END', 'THEN', 'ELSE', 'FI', 'ENDWH', ']'},
	"('OtherTerm', 'AddOp Exp')": {'+', '-'},
	"('Term', 'Factor OtherFactor')": {'(', 'ID', 'INTC'},
	"('OtherFactor', 'ε')": {'DO', ';', ')', ',', '-', '<', '=', 'END', 'THEN', '+', 'FI', 'ELSE', 'ENDWH', ']'},
	"('OtherFactor', 'MultOp Term')": {'/', '*'},
	"('Factor', '( Exp )')": {'('},
	"('Factor', 'INTC')": {'INTC'},
	"('Factor', 'Variable')": {'ID'},
	"('Variable', 'ID VariMore')": {'ID'},
	"('VariMore', 'ε')": {'DO', ';', '-', '=', 'END', '/', 'THEN', 'FI', 'ENDWH', '*', ')', ',', '<', '+', 'ELSE', ':=', ']'},
	"('VariMore', '[ Exp ]')": {'['},
	"('VariMore', '. FieldVar')": {'.'},
	"('FieldVar', 'ID FieldVarMore')": {'ID'},
	"('FieldVarMore', 'ε')": {'DO', ';', '-', '=', 'END', '/', 'THEN', 'FI', 'ENDWH', '*', ')', ',', '<', '+', 'ELSE', ':=', ']'},
	"('FieldVarMore', '[ Exp ]')": {'['},
	"('CmpOp', '<')": {'<'},
	"('CmpOp', '=')": {'='},
	"('AddOp', '+')": {'+'},
	"('AddOp', '-')": {'-'},
	"('MultOp', '*')": {'*'},
	"('MultOp', '/')": {'/'},
}