predict_sets = {
	('Program', 'ProgramHead DeclarePart ProgramBody .'): {'PROGRAM'},
	('ProgramHead', 'PROGRAM ProgramName'): {'PROGRAM'},
	('ProgramName', 'ID'): {'ID'},
	('DeclarePart', 'TypeDec VarDec ProcDec'): {'BEGIN', 'TYPE', 'PROCEDURE', 'VAR'},
	('TypeDec', 'ε'): {'BEGIN', 'PROCEDURE', 'VAR'},
	('TypeDec', 'TypeDeclaration'): {'TYPE'},
	('TypeDeclaration', 'TYPE TypeDecList'): {'TYPE'},
	('TypeDecList', 'TypeId = TypeName ; TypeDecMore'): {'ID'},
	('TypeDecMore', 'ε'): {'BEGIN', 'PROCEDURE', 'VAR'},
	('TypeDecMore', 'TypeDecList'): {'ID'},
	('TypeId', 'ID'): {'ID'},
	('TypeName', 'BaseType'): {'INTEGER', 'CHAR'},
	('TypeName', 'StructureType'): {'RECORD', 'ARRAY'},
	('TypeName', 'ID'): {'ID'},
	('BaseType', 'INTEGER'): {'INTEGER'},
	('BaseType', 'CHAR'): {'CHAR'},
	('StructureType', 'ArrayType'): {'ARRAY'},
	('StructureType', 'RecType'): {'RECORD'},
	('ArrayType', 'ARRAY [ Low .. Top ] OF BaseType'): {'ARRAY'},
	('Low', 'INTC'): {'INTC'},
	('Top', 'INTC'): {'INTC'},
	('RecType', 'RECORD FieldDecList END'): {'RECORD'},
	('FieldDecList', 'BaseType IdList ; FieldDecMore'): {'INTEGER', 'CHAR'},
	('FieldDecList', 'ArrayType IdList ; FieldDecMore'): {'ARRAY'},
	('FieldDecMore', 'ε'): {'END'},
	('FieldDecMore', 'FieldDecList'): {'ARRAY', 'INTEGER', 'CHAR'},
	('IdList', 'ID IdMore'): {'ID'},
	('IdMore', 'ε'): {';'},
	('IdMore', ', IdList'): {','},
	('VarDec', 'ε'): {'BEGIN', 'PROCEDURE'},
	('VarDec', 'VarDeclaration'): {'VAR'},
	('VarDeclaration', 'VAR VarDecList'): {'VAR'},
	('VarDecList', 'TypeName VarIdList ; VarDecMore'): {'RECORD', 'ARRAY', 'INTEGER', 'ID', 'CHAR'},
	('VarDecMore', 'ε'): {'BEGIN', 'PROCEDURE'},
	('VarDecMore', 'VarDecList'): {'RECORD', 'ARRAY', 'INTEGER', 'ID', 'CHAR'},
	('VarIdList', 'ID VarIdMore'): {'ID'},
	('VarIdMore', 'ε'): {';'},
	('VarIdMore', ', VarIdList'): {','},
	('ProcDec', 'ε'): {'BEGIN'},
	('ProcDec', 'ProcDeclaration'): {'PROCEDURE'},
	('ProcDeclaration', 'PROCEDURE ProcName ( ParamList ) ; ProcDecPart ProcBody ProcDecMore'): {'PROCEDURE'},
	('ProcDecMore', 'ε'): {'BEGIN'},
	('ProcDecMore', 'ProcDeclaration'): {'PROCEDURE'},
	('ProcName', 'ID'): {'ID'},
	('ParamList', 'ε'): {')'},
	('ParamList', 'ParamDecList'): {'RECORD', 'ARRAY', 'INTEGER', 'ID', 'CHAR', 'VAR'},
	('ParamDecList', 'Param ParamMore'): {'RECORD', 'ARRAY', 'INTEGER', 'ID', 'CHAR', 'VAR'},
	('ParamMore', 'ε'): {')'},
	('ParamMore', '; ParamDecList'): {';'},
	('Param', 'TypeName FormList'): {'RECORD', 'ARRAY', 'INTEGER', 'ID', 'CHAR'},
	('Param', 'VAR TypeName FormList'): {'VAR'},
	('FormList', 'ID FidMore'): {'ID'},
	('FidMore', 'ε'): {';', ')'},
	('FidMore', ', FormList'): {','},
	('ProcDecPart', 'DeclarePart'): {'BEGIN', 'TYPE', 'PROCEDURE', 'VAR'},
	('ProcBody', 'ProgramBody'): {'BEGIN'},
	('ProgramBody', 'BEGIN StmList END'): {'BEGIN'},
	('StmList', 'Stm StmMore'): {'IF', 'ID', 'READ', 'WRITE', 'WHILE', 'RETURN'},
	('StmMore', 'ε'): {'FI', 'ELSE', 'ENDWH', 'END'},
	('StmMore', '; StmList'): {';'},
	('Stm', 'ConditionalStm'): {'IF'},
	('Stm', 'LoopStm'): {'WHILE'},
	('Stm', 'InputStm'): {'READ'},
	('Stm', 'OutputStm'): {'WRITE'},
	('Stm', 'ReturnStm'): {'RETURN'},
	('Stm', 'ID AssCall'): {'ID'},
	('AssCall', 'AssignmentRest'): {'.', '[', ':='},
	('AssCall', 'CallStmRest'): {'('},
	('AssignmentRest', 'VariMore := Exp'): {'.', '[', ':='},
	('ConditionalStm', 'IF RelExp THEN StmList ELSE StmList FI'): {'IF'},
	('LoopStm', 'WHILE RelExp DO StmList ENDWH'): {'WHILE'},
	('InputStm', 'READ ( Invar )'): {'READ'},
	('Invar', 'ID'): {'ID'},
	('OutputStm', 'WRITE ( Exp )'): {'WRITE'},
	('ReturnStm', 'RETURN ( Exp )'): {'RETURN'},
	('CallStmRest', '( ActParamList )'): {'('},
	('ActParamList', 'ε'): {')'},
	('ActParamList', 'Exp ActParamMore'): {'(', 'ID', 'INTC'},
	('ActParamMore', 'ε'): {')'},
	('ActParamMore', ', ActParamList'): {','},
	('RelExp', 'Exp OtherRelE'): {'(', 'ID', 'INTC'},
	('OtherRelE', 'CmpOp Exp'): {'<', '='},
	('Exp', 'Term OtherTerm'): {'(', 'ID', 'INTC'},
	('OtherTerm', 'ε'): {'FI', 'THEN', ';', '<', 'ENDWH', 'DO', ',', 'ELSE', 'END', ')', ']', '='},
	('OtherTerm', 'AddOp Exp'): {'-', '+'},
	('Term', 'Factor OtherFactor'): {'(', 'ID', 'INTC'},
	('OtherFactor', 'ε'): {'FI', 'THEN', ';', '-', '<', '+', 'ENDWH', 'DO', ',', 'ELSE', 'END', ')', ']', '='},
	('OtherFactor', 'MultOp Term'): {'*', '/'},
	('Factor', '( Exp )'): {'('},
	('Factor', 'INTC'): {'INTC'},
	('Factor', 'Variable'): {'ID'},
	('Variable', 'ID VariMore'): {'ID'},
	('VariMore', 'ε'): {'FI', 'THEN', '-', '*', '+', 'ENDWH', ',', 'END', ')', '<', 'DO', 'ELSE', ':=', '/', ';', ']', '='},
	('VariMore', '[ Exp ]'): {'['},
	('VariMore', '. FieldVar'): {'.'},
	('FieldVar', 'ID FieldVarMore'): {'ID'},
	('FieldVarMore', 'ε'): {'FI', 'THEN', '-', '*', '+', 'ENDWH', ',', 'END', ')', '<', 'DO', 'ELSE', ':=', '/', ';', ']', '='},
	('FieldVarMore', '[ Exp ]'): {'['},
	('CmpOp', '<'): {'<'},
	('CmpOp', '='): {'='},
	('AddOp', '+'): {'+'},
	('AddOp', '-'): {'-'},
	('MultOp', '*'): {'*'},
	('MultOp', '/'): {'/'},
}